### ISSUE TITLE
Selecting a different Mod type crashes DAW instantly

### ISSUE THREAD

**Issue by eisbaer23** [Mrugalla/NEL-19#10]
Trying to change a Mod (both) using the mouse crashes DAW instantly, not even a nice message with error codes or anything useful to paste here. :-/
The random function (the big one) uses different Mods w/o problems, it's just selecting one on purpose that does it.

Win7 64bit, Reaper 7.0 rc4 64bit, NEL September 25 2023 build.

**Comment by Mrugalla** [comment]
Hey, I just solved a different problem where some people couldn't load the version with the correct build date in their DAWs. Are you sure you had the new build? Was it shown like that on the interface of the plugin?

Because I just tested changing the modulators in reaper v6.82 and unfortunately couldn't reproduce the issue so far

**Comment by eisbaer23** [comment]
Yes, the build info I used in my issue ticket is what I had on screen, and I did see about the two builds in the archive.
I'm gonna clean up, redownload the latest archive and try again.

**Comment by eisbaer23** [comment]
Installed a portable v6.82 64bit just in case, same thing as soon as I click a new Mod, NEL takes everything down with it (or so it seems). But this time I had some error message:
  Problem Event Name:	APPCRASH
  Application Name:	reaper.exe
  Application Version:	6.8.2.0
  Application Timestamp:	64e60464
  Fault Module Name:	NEL.vst3
  Fault Module Version:	1.0.0.0
  Fault Module Timestamp:	6511ab6c
  Exception Code:	c0000005
  Exception Offset:	00000000002f89f9
  OS Version:	6.1.7601.2.1.0.256.1
  Locale ID:	1033
  Additional Information 1:	6318
  Additional Information 2:	631823efa50261aa2c63d8dec3d713a6
  Additional Information 3:	61b4
  Additional Information 4:	61b4cf7510e1c353b1bd82a195d223eb

I'll try on a Win10 laptop later.

**Comment by Mrugalla** [comment]
i wish i knew what all that even means^^ but hey, it can't be too complicated. selecting components creates and deletes some GUI objects. I guess maybe I made a little mistake there that is only revealed on some computers. I'll look at the code a little closer again and tell you if I found and fixed something! thx for telling me about it

**Comment by eisbaer23** [comment]
Whatever you did, it fixed it. Either by chance or you did found out what it was. ^_^;;
I was able to select all six options from both Mods. Perfect.

**Comment by eisbaer23** [comment]
Closing the issue.
