### ISSUE TITLE
Unable to build on NixOS

### ISSUE THREAD

**Issue by magnetophon** [Mrugalla/NEL-19#4]
Thanks for the plugin!

Unfortunately I'm unable to build it.

Cmake chokes on [this line](https://github.com/Mrugalla/NEL-19/blob/master/CMakeLists.txt#L14) with the error ``Unknown CMake command "juce_add_plugin".``
I made JUCE available by doing 
```
sed -i 's@add_subdirectory ("G:/PluginDevelopment/JUCE" "JUCE")@add_subdirectory(JUCE)@' CMakeLists.txt
```
JUCE is actually in that directory, as far as I can tell.

Any ideas?

**Comment by Mrugalla** [comment]
i'm not very good at all this cmake stuff but it seems to me like this is the line that adds all the JUCE files to the project. so you'd just have to adjust this to match your JUCE folder or something. sorry that i can't fix this to work automatically right now, but cmake and i are really no friends yet. this cmake-file is very much a work-in-progress thing. if you know how to generalize this kinda stuff, send a pull request

**Comment by magnetophon** [comment]
OK, thanks.

I'm way worse in this whole cmake thing; I never even wrote one.

As far as I can tell JUCE gets correctly added to the project.
That is: this solution works for other plugins.

I don' t know how to check though.
