### ISSUE TITLE
Building on linux

### ISSUE THREAD

**Issue by farlukar** [Mrugalla/NEL-19#9]
Using the linux makefile threw a gcc error for me (kubuntu 23.04/gcc 12.3.0) , but changing ConvolutionFilter.h:175 to
`		using Convolution = oversampling::Convolution<Float>;`
made it compile without a problem.

(Sorry, I can't be arsed to do the whole forking/pull request business for one line of code)

**Comment by Mrugalla** [comment]
thx for letting me know :) but could you give me the file that you built so that i can put it in the release section here pls?

**Comment by farlukar** [comment]
Sure!
[NEL.vst3.tar.gz](https://github.com/Mrugalla/NEL-19/files/12801412/NEL.vst3.tar.gz)

**Comment by Mrugalla** [comment]
sweet :) thx
